services:
  postgres:
    image: postgres:16.3-alpine
    container_name: products_postgres
    environment:
      POSTGRES_USER: ordersys_user
      POSTGRES_PASSWORD: ofirnah
      POSTGRES_DB: products_db
    ports:
      - "5435:5432"
    volumes:
      - products_postgres_data:/var/lib/postgresql/data

volumes:
  products_postgres_data: